# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20171220_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='myurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
